name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:

    unit-testing:
        strategy:
          matrix:
            nodejs_version: [20, 23]
            operating_system: [ubuntu-latest, macos-latest]
            exclude:
              - nodejs_version: 23
                operating_system: macos-latest
        name: Unit Testing
        runs-on: ${{ matrix.operating_system }}
        steps:

        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS Version
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.nodejs_version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          if: ${{ always() }}
          uses: actions/upload-artifact@v7
          with:
            name: Mocha-Test-Result-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}
            path: test-results.xml

    code-coverage:
        name: code-coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS Version
          uses: actions/setup-node@v6
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Code Coverage
          run: npm run coverage
          
        - name: Archive Test Result
          if: ${{ always() }}
          uses: actions/upload-artifact@v7
          with:
            name: Code-Coverage-Result
            path: ./coverage
            # retention-days: 5 ## Optional retention